parameters:
    python_api_url: '%env(PYTHON_API_URL)%'
    python_api_key: '%env(PYTHON_API_KEY)%'
    kernel.runtime_mode: '%env(APP_RUNTIME)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
    App\Service\PythonPredictionService:
        arguments:
            $pythonApiUrl: '%python_api_url%'
            $pythonApiKey: '%python_api_key%'